spring:
  datasource:
    url: jdbc:mysql://localhost:3306/derdimET?useSSL=false&serverTimezone=UTC
    username: root
    password: 88888888
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
server:
  port: 8080
